In [5]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [4]:
myarr=np.array([1,2,3])

In [5]:
myarr

array([1, 2, 3])

In [6]:
print(myarr)

[1 2 3]


In [7]:
print(type(myarr))

<class 'numpy.ndarray'>


In [9]:
# making an array of zeros and ones
z=np.ones((3,4),dtype=np.int8)
print(z)
z.shape

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


(3, 4)

In [6]:
# arange method used for a range of array
a=np.arange(10,100)

In [8]:
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [12]:
# having range of numbers between 2 numbers (start, end, no range)
b=np.linspace(1,2,num=5)
print(b)
#if you dont want end number ie 2
c=np.linspace(1,2,num=5,endpoint=False)
print(c)

[1.   1.25 1.5  1.75 2.  ]
[1.  1.2 1.4 1.6 1.8]


In [15]:
d=np.array([np.arange(1,5),np.arange(11,15)])
print(d)
print(d[0,2])

[[ 1  2  3  4]
 [11 12 13 14]]
3


In [18]:
# selecting the subsets from the above 2D array using slicing
e=np.array(d[:,1:3])
print(e)

[[ 2  3]
 [12 13]]


In [20]:
f=np.array([np.arange(1,37)])
print(f)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36]]


In [23]:
# reshaping the array to 3D
g=f.reshape(3,4,3) #np.reshape(f,(3,4,3))
print(g)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


In [30]:
# 3D array ke middle ka middle ka middle
print(g[::2,1::2,1::2])

[[[ 5]
  [11]]

 [[29]
  [35]]]


In [7]:
# fancy indexing
i=[1,2,3]
#print(a[0,i])

In [9]:
# fancy indexes having true or false in their data
#i=np.array([False,False,True]) # this is known as boolean indexes

b=a>30
print(b)

[False False False False False False False False False False False False
 False False False False False False False False False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
