In [1]:
import numpy as np

g=np.arange(1,37)
# to change a multi D array to 1 D, this method copy of array so slow
c=g.flatten()  # parameters: F=column, K=size wise 
print(c)

c=np.ravel(g,order="F") # it will not create a copy, but a view therefore c me change toh a me bhi change

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [2]:
a=np.arange(1,6)
b=np.arange(11,16)

# concatenate func.
c=np.concatenate((a,b)) # default axis : 0
print(c)                # hstack(axis=1) and vstack(axis=0) same as concatenation

[ 1  2  3  4  5 11 12 13 14 15]


In [3]:
c=np.stack((a,b),axis=0)
print(c)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [4]:
d=np.arange(1,28).reshape(3,3,3)
e=np.arange(11,20).reshape(1,3,3)

c=np.concatenate((a,b))
print(c)

[ 1  2  3  4  5 11 12 13 14 15]


In [8]:
e=np.arange(1,28)

s=np.split(e,9)
print(s)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15]), array([16, 17, 18]), array([19, 20, 21]), array([22, 23, 24]), array([25, 26, 27])]
