In [2]:
import numpy as np

# problem 1: Represent the data in the given sheet into an appropriate NumPy array so that you can perform the following actions on it.
temp=np.array([12,22,6,28,10,21,10,31,12,32,6,26,15,23,9,22,8,23,7,27,-13,28,7,23,14,31,9,26,11,29,8,22,10,21,14,24,11,28,13,29,8,22,11,25,9,21,8,23,8,30,14,29,8,32,15,20,12,30,8,21,10,26,10,24,8,23,12,32,14,25,9,23,11,26,12,29,9,32,9,30,11,30,9,24,12,21,9,25,14,24,13,24,11,25,6,20,10,24,13,24,7,25,12,32,9,22,12,28,15,21,14,20,2,20,6,20,7,20,8,21,4,20,5,2,21,5,5,20,8,18,5,19,5,19,8,20,2,8,19,5,4,19,4,21,5,19,5,19,6,21,8,5,22,7,3,19,5,21,7,21,5,19,4,20,6,5,21,6,7,21,10,18,-10,20,12,18,12,19,7,71,22,9,11,20,12,21,11,22,9,18,10,19,8,8,20,8,7,22,12,21,7,22,12,20,11,20,10,12,19,11,7,22,11,22,7,21,12,18,10,18,10,8,18,10])

In [3]:
tempGrid=temp.reshape(4,4,7,2)

In [4]:
print(tempGrid)

[[[[ 12  22]
   [  6  28]
   [ 10  21]
   [ 10  31]
   [ 12  32]
   [  6  26]
   [ 15  23]]

  [[  9  22]
   [  8  23]
   [  7  27]
   [-13  28]
   [  7  23]
   [ 14  31]
   [  9  26]]

  [[ 11  29]
   [  8  22]
   [ 10  21]
   [ 14  24]
   [ 11  28]
   [ 13  29]
   [  8  22]]

  [[ 11  25]
   [  9  21]
   [  8  23]
   [  8  30]
   [ 14  29]
   [  8  32]
   [ 15  20]]]


 [[[ 12  30]
   [  8  21]
   [ 10  26]
   [ 10  24]
   [  8  23]
   [ 12  32]
   [ 14  25]]

  [[  9  23]
   [ 11  26]
   [ 12  29]
   [  9  32]
   [  9  30]
   [ 11  30]
   [  9  24]]

  [[ 12  21]
   [  9  25]
   [ 14  24]
   [ 13  24]
   [ 11  25]
   [  6  20]
   [ 10  24]]

  [[ 13  24]
   [  7  25]
   [ 12  32]
   [  9  22]
   [ 12  28]
   [ 15  21]
   [ 14  20]]]


 [[[  2  20]
   [  6  20]
   [  7  20]
   [  8  21]
   [  4  20]
   [  5   2]
   [ 21   5]]

  [[  5  20]
   [  8  18]
   [  5  19]
   [  5  19]
   [  8  20]
   [  2   8]
   [ 19   5]]

  [[  4  19]
   [  4  21]
   [  5  19]
   [  5  19]
   [  6  21]
 

In [5]:
tempGrid.ndim

4

In [6]:
# problem 2: Write the dimensions and shape of the NumPy array that you have created.

np.shape(tempGrid)

(4, 4, 7, 2)

In [7]:
# problem 3: Print the daily temperatures for the first week of each month.
print(tempGrid[:,0])  # (month , week , day , temp)

[[[ 12  22]
  [  6  28]
  [ 10  21]
  [ 10  31]
  [ 12  32]
  [  6  26]
  [ 15  23]]

 [[ 12  30]
  [  8  21]
  [ 10  26]
  [ 10  24]
  [  8  23]
  [ 12  32]
  [ 14  25]]

 [[  2  20]
  [  6  20]
  [  7  20]
  [  8  21]
  [  4  20]
  [  5   2]
  [ 21   5]]

 [[  7  21]
  [ 10  18]
  [-10  20]
  [ 12  18]
  [ 12  19]
  [  7  71]
  [ 22   9]]]


In [8]:
# problem 4: Print the temperatures for Tuesday of each month.
print(tempGrid[:,:,1])

[[[ 6 28]
  [ 8 23]
  [ 8 22]
  [ 9 21]]

 [[ 8 21]
  [11 26]
  [ 9 25]
  [ 7 25]]

 [[ 6 20]
  [ 8 18]
  [ 4 21]
  [ 5 21]]

 [[10 18]
  [12 21]
  [12 21]
  [11 22]]]


In [9]:
# problem 5: Print only the maximum temperature for all the weekdays of Dec and Feb.
print(tempGrid[1::2,:,:,1])

[[[30 21 26 24 23 32 25]
  [23 26 29 32 30 30 24]
  [21 25 24 24 25 20 24]
  [24 25 32 22 28 21 20]]

 [[21 18 20 18 19 71  9]
  [20 21 22 18 19  8  8]
  [22 21 22 20 20 12 11]
  [22 22 21 18 18  8 10]]]


In [18]:
# problem 6: Print all the days along with the week number in November when the minimum temperature was less than 8 degrees.
for i in range(0,4):
    for j in range(0,7):
        lt=tempGrid[0,i,j,0]
        if np.any(lt<8):
            print(f"week: {i+1}      day: {j+1}      temperature: {lt}")

week: 1      day: 2      temperature: 6
week: 1      day: 6      temperature: 6
week: 2      day: 3      temperature: 7
week: 2      day: 4      temperature: -13
week: 2      day: 5      temperature: 7


In [11]:
# problem 7: Print all the weeks in Dec and Jan where the maximum temperature has crossed a threshold of 20 degrees.
for k in range(1,3):
    for i in range(4):
        for j in range(7):
            lt=tempGrid[k,i,j,:]
            if np.any(lt>20):
                print(f"month: {k+1}        week: {i+1}")

month: 2        week: 1
month: 2        week: 1
month: 2        week: 1
month: 2        week: 1
month: 2        week: 1
month: 2        week: 1
month: 2        week: 1
month: 2        week: 2
month: 2        week: 2
month: 2        week: 2
month: 2        week: 2
month: 2        week: 2
month: 2        week: 2
month: 2        week: 2
month: 2        week: 3
month: 2        week: 3
month: 2        week: 3
month: 2        week: 3
month: 2        week: 3
month: 2        week: 3
month: 2        week: 4
month: 2        week: 4
month: 2        week: 4
month: 2        week: 4
month: 2        week: 4
month: 2        week: 4
month: 3        week: 1
month: 3        week: 1
month: 3        week: 3
month: 3        week: 3
month: 3        week: 3
month: 3        week: 4
month: 3        week: 4
month: 3        week: 4
